// src/lib/components/Sidebar.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  export let open = false;

  const dispatch = createEventDispatcher();
</script>

<div class="fixed top-0 right-0 h-screen bg-accent-800 text-text-400 overflow-x-hidden sidebar" class:open-sidebar={open} class:close-sidebar={!open} >
  <div>
    <button on:click={() => dispatch("sidebar-close", false)} class="absolute top-0 right-0 m-3 text-2xl">&times;</button>
    <nav class="px-12 py-24 text-2xl">
      <div class="flex flex-col gap-3 mb-3">
        <a href="/">Home</a>
        <a href="/prs">PRs</a>
      </div>
      <hr />
      <div class="flex flex-col gap-3 mb-3">
        <a href="/roadmap">Roadmap</a>
      </div>
    </nav>
  </div>
</div>

<style>
  :root {
    --sidebar-width: 33.333333vw;
  }

  @media (max-width: 1024px) {
    :root {
      --sidebar-width: 100vw;
    }
  }

  .sidebar {
    transition: width 0.5s;
  }

  .open-sidebar {
    width: var(--sidebar-width);
  }

  .close-sidebar {
    width: 0px;
  }
</style>

// components/Sidebar.vue
<template>
  <div class="absolute top-0 right-0 bg-accent-800 overflow-x-hidden">
    <Transition name="sidebar">
      <div v-show="props.activated" id="sidebar" class="h-screen">
        <button @click="emits('hide-sidebar')" class="text-lg absolute top-0 right-0 m-3">&times;</button>
        <nav class="ml-12 mt-24 flex flex-col text-2xl gap-3">
          <NuxtLink to="/">Home</NuxtLink>
          <NuxtLink to="/prs">PRs</NuxtLink>
        </nav>
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  activated: {
    type: Boolean,
    required: true,
  },
});
const emits = defineEmits([ "hide-sidebar" ]);
</script>

<style>
:root {
  --sidebar-width: 100vw;
}
@media (min-width: 1024px) {
  :root {
    --sidebar-width: 33.333333vw;
  }
}

#sidebar {
  width: var(--sidebar-width);
}

.sidebar-enter-active {
  animation: sidebar 0.5s;
}
.sidebar-leave-active {
  animation: sidebar 0.5s reverse;
}

@keyframes sidebar {
  0% {
    width: 0px;
  }
  100% {
    width: var(--sidebar-width);
  }
}
</style>
