// pages/m/[movement].vue
<template>
  <div class="text-xl">
    <header class="flex flex-col items-center my-8 font-semibold">
      <h1 class="font-semibold">{{ toTitle(route.params.movement) }}</h1>
    </header>
    <div class="flex flex-col items-center">
      <LabeledInput label="Max" input-id="max-input">
        <NumberInput
          @value-change="(weight) => saveMax(weight)"
          :object-keys="['prs', route.params.movement]"
        />
      </LabeledInput>
      <Percentages
        v-show="prs[route.params.movement]"
        :weight="typeof prs[route.params.movement] === 'number' ? prs[route.params.movement] : 0"
        class="w-5/6 md:w-2/3 max-md:text-2xl"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
const { $getSaveData, $setSaveData } = useNuxtApp();
const route = useRoute();

let prs = ref(await $getSaveData("prs"));

watch(prs.value, (newPrs) => {
  $setSaveData("prs", toRaw(newPrs));
});

function saveMax(weight: number) {
  prs.value[route.params.movement] = weight;
}

function toTitle(s: string) {
  return s
    .replace(/([A-Z])/g, " $1")
    .replace(/^./g, (str) => str.toUpperCase());
}
</script>

// src/routes/m/[movement]/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { page } from "$app/stores";
  import { browser } from "$app/environment";

  import { prs } from "$lib/indy";

  import PercentageTable from "$components/PercentageTable.svelte";
  import LabeledInput from "$components/LabeledInput.svelte";

  let weight = 0;
  let maxes = [0, 0, 0, 0];
  let logOpen = false;

  onMount(async () => {
    prs.getItem($page.params.movement).then((value: any) => {
      if (value) {
        maxes = value;
      }
      weight = maxes[0];
    });
  });

  function openLogMenu(open: boolean) {
    logOpen = open;
  }

  function savePRs() {
    if (browser) {
      prs.setItem($page.params.movement, maxes);
      weight = maxes[0];
    }
  }

  function toTitleCase(text: string) {
    return text.replace(/([A-Z])/g, " $1").replace(/^./g, (str) => str.toUpperCase());
  }
</script>

<svelte:head>
  <title>PRs - {toTitleCase($page.params.movement)}</title>
</svelte:head>

<div class="flex flex-col text-text-400 items-center">
  <h1 class="my-8 text-xl font-semibold">{toTitleCase($page.params.movement)}</h1>
  <div class="my-3">
    <button on:click={() => openLogMenu(true)} class="p-2 bg-accent-500 rounded-lg"
      >Log Score</button
    >
  </div>
  <PercentageTable weight={typeof weight !== "string" ? weight : 0} />
  {#if logOpen}
    <div
      class="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 p-3 bg-background-800 rounded-lg"
    >
      <h2 class="mb-1.5">Log Scores</h2>
      <div class="[&>*]:mb-2">
        <LabeledInput inputId="one-rep" label="1 Rep Max: ">
          <input id="one-rep" type="number" bind:value={maxes[0]} />
        </LabeledInput>
        <LabeledInput inputId="two-rep" label="2 Rep Max: ">
          <input id="two-rep" type="number" bind:value={maxes[1]} />
        </LabeledInput>
        <LabeledInput inputId="three-rep" label="3 Rep Max: ">
          <input id="three-rep" type="number" bind:value={maxes[2]} />
        </LabeledInput>
        <LabeledInput inputId="five-rep" label="5 Rep Max: ">
          <input id="five-rep" type="number" bind:value={maxes[3]} />
        </LabeledInput>
      </div>
      <button
        on:click={() => {
          savePRs();
          openLogMenu(false);
        }}
        class="p-1 px-2 bg-accent-500 rounded-lg"
      >
        Save
      </button>
    </div>
  {/if}
</div>
